# Generated by Django 4.0 on 2022-05-23 15:15

from django.db import migrations, models
import plasmaapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=30)),
                ('messages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1_name', models.CharField(max_length=20)),
                ('member1_email', models.EmailField(max_length=254)),
                ('member1_phone', models.TextField()),
                ('member1_college', models.TextField()),
                ('member1_branch', models.CharField(max_length=40)),
                ('paid_amount', models.IntegerField()),
                ('payment_mode', models.TextField()),
                ('payment_date', models.DateField()),
                ('paid_by', models.TextField()),
                ('utr_upi_no', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=plasmaapp.models.file)),
            ],
        ),
        migrations.CreateModel(
            name='registration_details',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=25)),
                ('member1_name', models.CharField(max_length=20)),
                ('member1_email', models.EmailField(max_length=254)),
                ('member1_phone', models.TextField()),
                ('member1_college', models.TextField()),
                ('member1_branch', models.CharField(max_length=40)),
                ('member2_name', models.CharField(max_length=20)),
                ('member2_email', models.EmailField(max_length=254)),
                ('member2_phone', models.TextField()),
                ('member2_college', models.TextField()),
                ('member2_branch', models.CharField(max_length=40)),
                ('member3_name', models.CharField(max_length=20)),
                ('member3_email', models.EmailField(max_length=254)),
                ('member3_phone', models.TextField()),
                ('member3_college', models.TextField()),
                ('member3_branch', models.CharField(max_length=40)),
                ('member4_name', models.CharField(max_length=20)),
                ('member4_email', models.EmailField(max_length=254)),
                ('member4_phone', models.TextField()),
                ('member4_college', models.TextField()),
                ('member4_branch', models.CharField(max_length=40)),
                ('total_amount', models.CharField(max_length=8)),
                ('selected_event', models.TextField()),
                ('hospitality', models.TextField()),
            ],
        ),
    ]
